### ISSUE TITLE
Teleport doesn't work

### ISSUE THREAD

**Issue by neizvedaniydag** [marianydesign/Unity-WebXR-Teleportation-and-SmoothLocomotion#1]
Hi! I ran into a problem that the teleport for my samsung odyssey glasses does not work. What could be the problem?

**Comment by pascalmariany** [comment]
> Hi! I ran into a problem that the teleport for my samsung odyssey glasses does not work. What could be the problem?

How did you test? Within Unity or did you export the generated files and hosting it online? I'm curious if you get any errors in the console of you would try it directly via Unity.
In the browser you can also do some debugging.

**Comment by neizvedaniydag** [comment]
I used the build of the application and did not use debugging, I 'll take a look now

**Comment by neizvedaniydag** [comment]
I'm thinking of buying other ar glasses to do development. Could you please check the performance of my teleport in itch io? https://akaevamir913.itch.io/webxr-teleport . Maybe the glasses are the problem.

**Comment by pascalmariany** [comment]
Sure thing! I'll have a look into this tomorrow.

**Comment by neizvedaniydag** [comment]
Thank you for your reply. I found out what the problem was. It turned out that the thumbstick must be held before moving.

**Comment by pascalmariany** [comment]
Good job 💪🏼
